경북대 Android_권성찬_1주차_과제
kakao-tech-campus-2nd-step2/android-contacts pull request #14
Opened 2024-06-28 05:13 UTC by ksc1008

## 코드 작성 시 어려웠던 점

- 여전히 메소드를 작게 기능 단위로 분리하는게 익숙하지 않은 것 같습니다. 
- 기능 단위로 커밋을 남기고, convention을 지키면서 변경사항을 명시하는 것이 아직은 미흡하고 연습이 필요할 것 같습니다.

## 멘토 님이 중점적으로 리뷰해줬으면 하는 부분

- 많은 코드를 하나의 액티비티 안에 넣은 것 같습니다. 액티비티 안에 들어간 기능들을 다른 클래스나 코드로 분리시키는게 더 좋을지 알고 싶습니다.
- 코틀린 변수도 마찬가지지만 특히나 레이아웃 요소 id를 네이밍하는 것이 익숙치 않아 가독성이 떨어지는 것 같습니다. 레이아웃 id를 명명하는 좋은 방식 같은게 있다면 알고 싶습니다.

## 구현 화면
![Screenshot_20240627_172523_Contacts](https://github.com/kakao-tech-campus-2nd-step2/android-contacts/assets/54511614/72997fcc-dc1f-45d2-946f-c1dcb52a18ab)
![Screenshot_20240627_172633_Contacts](https://github.com/kakao-tech-campus-2nd-step2/android-contacts/assets/54511614/036110e5-70d6-45cc-960d-efa4f5c49cf7)
![Screenshot_20240627_172642_Contacts](https://github.com/kakao-tech-campus-2nd-step2/android-contacts/assets/54511614/8e4b195d-3828-436c-995c-ccd0d59f99bf)
![Screenshot_20240625_163702_Contacts](https://github.com/kakao-tech-campus-2nd-step2/android-contacts/assets/54511614/b234935d-1a99-4b98-98df-94d1f3d888d2)

2024-06-30 11:32 UTC, mkSpace requested changes
안녕하세요 민철님. 앞으로 6주 동안 코드 리뷰를 맡게 된 제리 멘토입니다.

긴 시간 공 들여서 깔끔한 코드를 작성해주셔서 리뷰를 할 때 매우 편했습니다. 더욱이나 테스트 또한 작성해주셔서 매우 놀랐습니다. 

이번 리뷰에는 최대한 강의 시간에 진행한 내용을 토대로 리뷰를 작성했습니다. RecyclerView와 같은 부분은 리뷰가 미흡할 수 있으니 양해 부탁드립니다.

리뷰 남겨드리니 읽어보시고 편하게 의견 남겨주세요!

---

우선 민철님이 메소드를 작게 기능 단위로 분리하는게 익숙하지 않은 것 같다고 하셨는데 충분히 잘 하셨다고 생각이 듭니다. 메소드를 작게 유지하려다 보니 메소드의 양 자체가 많아진 것 같아 액티비티가 많이 커진것으로 느껴지셨을 겁니다. 이 부분은 추후에 아키텍처를 공부하면서 많은 부분 호전되니 지금 이 연습을 더 해보시는걸 추천드립니다.

그리고 액티비티가 커지다보니 분리의 필요성에 느끼고 계시는데 정말 좋은 고민이라고 생각됩니다. 하지만 섣불리 분리를 하다보면 하지 않으니만 못하다고 생각하실 수 있습니다. 또한 많은 기능을 직접 구현하고 계신데 사실 그보다 더 많은 부분을 개발 편의성을 위해 확장함수나 유틸리티성 객체를 많이 제공합니다. 우선은 그러한 확장함수를 찾아보시고 같은 로직들이 다른 화면들에서 반복되는 것들이 있을 때 분리를 고려해볼 수 있을 것 같습니다.

레이아웃 id나 변수 이름을 작명하는것은 정말 신경쓸 부분이 많죠. 사실 이 부분은 정답이 없는 것 같습니다. 다만 중요한 부분은 프로젝트 내에서 네이밍 부분이 일관성을 가져야 한다는 부분입니다. 저 같은 경우에는 프로젝트를 시작할 때 코드 컨벤션 및 네이밍 규칙들을 사전에 정의하고 프로젝트를 시작합니다. 이렇게 네이밍 관련 정책을 세운다면 오히려 제약사항때문에 네이밍을 빠르게 생각해낼 수 있을 겁니다.

충분히 잘 네이밍 해주셨고 일관성 있게 작성해주셨습니다. 👍

2024-06-30 11:32 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/AddContactActivity.kt
> +    companion object {
https://kotlinlang.org/docs/coding-conventions.html#class-layout
코틀린 공식 문서에서 companion object는 가장 마지막 순서에 배치하는걸 컨벤션으로 지정하고 있습니다. 맨 밑으로 이동하는게 좋겠네요

2024-06-30 11:32 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/AddContactActivity.kt
> +    private lateinit var genderInput: RadioGroup
RadioGroup인데 Input으로 끝나면 혼동의 여지가 있을 수 있겠네요. genderRadioGroup 정도로 표현해보면 어떨까요?

2024-06-30 11:32 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/AddContactActivity.kt
> +        const val GENDER_MALE = 1
성별 관련 상수를 넘버 형태로 정의해주셨네요. 위의 코드와 같이 생각해보면 RadioGroup의 index로 쉽게 접근하기 위한 아이디어로 생각됩니다. 하지만 이와 같은 부분은 다른 개발자가 볼 때 실수할 수 있는 요지가 있습니다. 
만약 기획이나 디자인의 변경에 의해 xml이 변경이 될 때 이 부분은 오류의 요지가 될 수 있습니다. 
index를 통해 View에 접근하는 방식말고 다른 방식으로 리팩토링 해 볼 수 있을것 같습니다.

2024-06-30 11:32 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/ContactInfoActivity.kt
> +            intent.getSerializableExtra(AddContactActivity.KEY_CONTACT) as Contact?
as Contact? 와 as? Contact는 어떤 차이가 있을까요?

2024-06-30 11:32 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/ContactInfoActivity.kt
> +        (phoneLayout[CONTACT_LAYOUT_VALUE_INDEX] as TextView?)?.text = contact.phoneNumber
index를 통한 View에 대한 접근은 최대한 피해야합니다! xml은 언제든지 변경될 수 있습니다.
TextView에 직접 접근해서 text를 변경하는게 나아보입니다!

2024-06-30 11:32 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/ContactListAdapter.kt
> +    val context: Context,
context는 사용하고 있지 않는것 같네요!

2024-06-30 11:32 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/ContactListAdapter.kt
> +        }
class-layout convention으로 볼 때 init block은 최상단으로 위치하는게 좋겠네요. 이 경우에는 각 View를 바로 초기화 하는 것도 좋겠네요.

2024-06-30 11:32 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/ContactListAdapter.kt
> +            textInsideImage.text = (contact.name).getOrNull(0).toString()
```suggestion
            textInsideImage.text = (contact.name).firstOrNull().toString()
```
getOrNull(0) 보단 firstOrNull()이 좀더 직관적으로 표현되는것 같네요 :)

2024-06-30 11:32 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/ContactsListActivity.kt
> +    private fun testAddContacts() {
테스트를 위해 작성하신 것 같은데 이 부분은 삭제해주세요!

2024-06-30 11:32 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/ContactsListActivity.kt
> +        helpMessageText.visibility = if (active) View.VISIBLE else View.GONE
안드로이드는 Visibility 관련 확장함수를 제공합니다.
```suggestion
        helpMessageText.isVisible = active
```
조금 더 직관적으로 표현할 수 있겠네요!

2024-06-30 11:32 UTC, mkSpace commented on app/src/main/res/layout/activity_addcontact.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
ConstraintLayout은 왠만한 경우라면 depth 1으로 모든 레이아웃을 표현할 수 있습니다. 다른 ViewGroup 중첩하지 않고 작성해 보시겠어요?

2024-06-30 11:32 UTC, mkSpace commented on app/src/main/res/layout/activity_addcontact.xml
> +            app:layout_constraintTop_toBottomOf="@id/input_birthday">
해당 ViewGroup의 부모 ViewGroup이 무엇인지 생각해보심 좋을것같아요

2024-06-30 11:32 UTC, mkSpace commented on app/src/main/res/layout/activity_addcontact.xml
> +            app:layout_constraintTop_toBottomOf="@id/input_name" />
이 코드또한 의미가 없겠네요

2024-06-30 11:32 UTC, mkSpace commented on app/src/main/res/layout/activity_addcontact.xml
> +        android:layout_width="match_parent"
부모 ViewGroup이 ConstraintLayout일 때 match_parent를 작성하는 방법은
layout_width = "0dp"
layout_constraintStart_toStartOf = "parent"
layout_constraintEnd_toEndOf = "parent"
로 작성할 수 있습니다.

2024-06-30 11:32 UTC, mkSpace commented on app/src/main/res/layout/activity_contact_info.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
여기도 충분히 1 depth로 작성해 볼 수 있겠네요.

2024-06-30 11:32 UTC, mkSpace commented on app/src/main/res/layout/activity_contacts_list.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
ConstraintLayout도 좋은데 이 화면을 구성할 떄 FrameLayout으로도 한 번 작성해보시길 추천드립니다.

2024-06-30 11:32 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/ContactListAdapter.kt
> +    private val contactList: MutableList<Contact>,
여기서 사용하는 ContactList는 Mutable 하지 않아도 되겠네요.
데이터를 여러 객체가 서로 공유할 때 수정 및 변경은 최대한 하나의 객체가 도맡는게 좋습니다.
민철님의 경우 이런 책임을 Activity가 갖는 것으로 보이네요. 그러면 ContactListAdapter는 캐싱의 용도로만 사용하는게 좋아보입니다.
```suggestion
    private val contactList: List<Contact>,
```

2024-06-30 11:32 UTC, mkSpace commented on app/src/main/res/layout/activity_addcontact.xml
> +        android:text="더보기"
hint 및 text 관련된 값은 strings.xml에 관리하는게 좋습니다. 추후 다국어 지원이나 키 추가 등에서 이점이 있습니다.

2024-07-01 03:08 UTC, ksc1008 commented on app/src/main/java/campus/tech/kakao/contacts/AddContactActivity.kt
> +    companion object {
수정하였습니다!

2024-07-01 03:08 UTC, ksc1008 commented on app/src/main/java/campus/tech/kakao/contacts/AddContactActivity.kt
> +    private lateinit var genderInput: RadioGroup
수정하였습니다!

2024-07-01 03:08 UTC, ksc1008 commented on app/src/main/java/campus/tech/kakao/contacts/AddContactActivity.kt
> +        const val GENDER_MALE = 1
GENDER 상수의 경우, 두 가지 용도로 사용하였습니다: 
첫째는 **Contact** 데이터 클래스에서 정수형으로 저장된 성별값의 성별을 판별하는 용도이고, 
두번째 용도는 그룹 레이아웃의 children을 참조할 때 쓰이는 index입니다.

코드를 수정하여 index를 통해 접근하지 않고 각 RadioButton을 직접 멤버변수로 할당하였습니다.
그러다 보니 Contact 클래스에서 쓰이는 상수가 액티비티에 정의되어 있는 것이 부적절하다 생각하여 해당 상수는 Contact 클래스로 옮겼습니다.

2024-07-01 03:08 UTC, ksc1008 commented on app/src/main/java/campus/tech/kakao/contacts/ContactInfoActivity.kt
> +            intent.getSerializableExtra(AddContactActivity.KEY_CONTACT) as Contact?
https://stackoverflow.com/questions/50836017/safe-cast-vs-cast-to-nullable 자주 혼동하는 개념이었는데 덕분에 다시한번 되짚어 봅니다. 감사합니다!
역직렬화가 정상적으로 수행되지 않았을 때 예외를 발생하는 것보다 null을 리턴하는 것이 더 적절하다고 생각해 해당 코드는 as? 구문으로 수정하였습니다.

2024-07-01 03:08 UTC, ksc1008 commented on app/src/main/java/campus/tech/kakao/contacts/ContactInfoActivity.kt
> +        (phoneLayout[CONTACT_LAYOUT_VALUE_INDEX] as TextView?)?.text = contact.phoneNumber
TextView를 따로 변수로 지정하여 직접 접근하게 수정하였습니다!

2024-07-01 03:09 UTC, ksc1008 commented on app/src/main/java/campus/tech/kakao/contacts/ContactListAdapter.kt
> +    val context: Context,
사용하지 않는 프로퍼티는 제거하였습니다.

2024-07-01 03:09 UTC, ksc1008 commented on app/src/main/java/campus/tech/kakao/contacts/ContactListAdapter.kt
> +        }
각 View를 바로 초기화하라는 것은 init 블럭을 사용하지 않고 프로퍼티 정의 구문에서 바로 초기화를 수행하라는 뜻일 까요?

2024-07-01 03:09 UTC, ksc1008 commented on app/src/main/java/campus/tech/kakao/contacts/ContactListAdapter.kt
> +            textInsideImage.text = (contact.name).getOrNull(0).toString()
수정하였습니다!

2024-07-01 03:09 UTC, ksc1008 commented on app/src/main/java/campus/tech/kakao/contacts/ContactsListActivity.kt
> +    private fun testAddContacts() {
수정하였습니다!

2024-07-01 03:09 UTC, ksc1008 commented on app/src/main/java/campus/tech/kakao/contacts/ContactsListActivity.kt
> +        helpMessageText.visibility = if (active) View.VISIBLE else View.GONE
수정하였습니다!

2024-07-01 03:09 UTC, ksc1008 commented on app/src/main/res/layout/activity_addcontact.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
더보기 메뉴의 Visibility를 수정하는 것과 같이 여러 View를 동시에 변경해야 하는 상황일 때, ViewGroup으로 묶지 않으면 모든 자식 뷰들을 일일이 수정해야 하여 불편함이 있었습니다.
이러한 경우에도 뷰 그룹을 활용하지 않고 depth를 줄이는게 더 나은 방향일까요?

2024-07-01 03:09 UTC, ksc1008 commented on app/src/main/res/layout/activity_addcontact.xml
> +            app:layout_constraintTop_toBottomOf="@id/input_birthday">
코드를 재사용하다 실수가 발생한 것 같습니다. 뷰 그룹을 해체하는 과정에서 수정하였습니다!

2024-07-01 03:10 UTC, ksc1008 commented on app/src/main/res/layout/activity_addcontact.xml
> +            app:layout_constraintTop_toBottomOf="@id/input_name" />
수정하였습니다!

2024-07-01 03:10 UTC, ksc1008 commented on app/src/main/res/layout/activity_addcontact.xml
> +        android:layout_width="match_parent"
수정하였습니다!

2024-07-01 03:10 UTC, ksc1008 commented on app/src/main/res/layout/activity_contact_info.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
수정하였습니다!

2024-07-01 03:10 UTC, ksc1008 commented on app/src/main/res/layout/activity_contacts_list.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
감사합니다! 이 후 FrameLayout을 활용할 상황이 있으면 활용해보겠습니다.

2024-07-01 03:10 UTC, ksc1008 commented on app/src/main/java/campus/tech/kakao/contacts/ContactListAdapter.kt
> +    private val contactList: MutableList<Contact>,
수정하였습니다!

2024-07-01 03:10 UTC, ksc1008 commented on app/src/main/res/layout/activity_addcontact.xml
> +        android:text="더보기"
수정하였습니다!

2024-07-01 09:11 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/AddContactActivity.kt
> +        const val GENDER_MALE = 1
네 좋습니다! enum class도 한 번 고려해보시면 좋겠네요

2024-07-01 09:11 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/ContactInfoActivity.kt
> +            intent.getSerializableExtra(AddContactActivity.KEY_CONTACT) as Contact?
제가 의도한 대로 잘 찾아서 공부하셨네요! 훌륭하십니다!

2024-07-01 09:12 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/ContactListAdapter.kt
> +        }
네네 맞습니다 :)

2024-07-01 09:16 UTC, mkSpace commented on app/src/main/res/layout/activity_addcontact.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
ConstraintLayout 설계 시 그것도 고려해서 Group을 제공하는데 활용해보시겠어요?

2024-07-01 09:17 UTC, mkSpace approved these changes

2024-07-03 09:24 UTC, closed without merging