강원대 Android_윤채원_1주차 과제
kakao-tech-campus-2nd-step2/android-contacts pull request #19
Opened 2024-06-28 06:44 UTC by settle54

2024-06-29 09:33 UTC, kold-brewed requested changes
안녕하세요 채원님 :)
6주동안 Step2 과제 진행을 도와드리게 된 콜드입니다.
2단계 목록 구성까지 열심히 작성해주셔서 알려드리고 싶은 부분도 많아진 것 같아요 ㅎㅎ
특히, object를 사용하지 않고 Activity의 결과를 받아와 목록을 표시하는 부분은 꼭 시도해보셨으면 합니다. 진행하면서 어려운 점은 언제든 코멘트 남겨주세요.

2024-06-29 09:33 UTC, kold-brewed commented on app/build.gradle.kts
> +        viewBinding = true
viewBinding 기능을 활성화 하셨군요! 실제 Activity에서 사용하지는 않으신 걸로 보이긴 합니다만, 어떤 이유에서 추가하셨는지 설명해주실 수 있을까요?

2024-06-29 09:33 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/contacts/Contact.kt
> +    var name: String, var phoneNumber: String, var mail: String = "",
작성해주신 코드에서 Contact의 쓰임새를 살펴보면 이름, 번호, 메일 등의 변수는 한번 할당되면 변경되지 않는 것처럼 보여요. 코틀린에서 프로퍼티를 정의하실 때에는 불필요하게 setter가 노출되지 않도록 var을 신중하게 사용해주시면 좋겠습니다.

2024-06-29 09:33 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/contacts/Contact.kt
> +            else -> throw IllegalArgumentException("Unknown field: $s")
안드로이드는 Exception이 발생하는 순간 앱 크래시로 이어집니다.
위와 같이 정의하실 경우, 혹시 모를 크래시에 대비하기 위해 contact[s]에 접근하는 모든 지점에서 예외처리가 필요해집니다.
else의 경우에 대한 처리방식을 조금 더 고민해주시면 좋을 것 같아요.

2024-06-29 09:33 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/contacts/Contact.kt
> +    }
코틀린에서 data class는 equals를 포함해 몇몇 메소드들을 개발자가 직접 정의해야하는 수고로움을 덜기 위해 사용합니다.

equals가 재정의된 것 자체가 잘못된 건 아니지만, data class에게 기대하는 equals의 동작과 달라지게 되면 의도치 않은 혼란을 겪을 수 있어보여요. 이 경우에는 data가 아닌 일반 class를 이용해 equals를 재정의하거나, 혹은 data class를 사용하되 name과 phoneNumber를 비교하는 별도 함수를 만들어 주시는 것을 추천드립니다.

2024-06-29 09:33 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/contacts/Contacts.kt
> +        if (findContact(infos[0], infos[1]) == -1) {
findContact 함수가 index를 반환하고 있지만, 호출부에서 index는 사용되지 않고 있어요.
중복 여부만 필요하다면 함수 반환형을 Boolean으로 변경하고 함수명도 그에 맞게 수정해 불필요한 정보가 노출되는 것을 막았으면 합니다. 또 클래스 내부에서만 사용하는 함수라면 가시성도 신경써주시면 좋을 것 같아요.

2024-06-29 09:33 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/contacts/Contact.kt
> +    operator fun get(s: String): String {
contact.name과 같이 변수에 바로 접근하지 않고 operator get을 쓰신 이유를 설명해주실 수 있을까요?

2024-06-29 09:33 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/contacts/ContactsAdapter.kt
> +class ContactsAdapter(private var contList: List<Contact>, private val listener: OnItemClickListener, private val longListener: OnItemLongClickListener): RecyclerView.Adapter<ContactsAdapter.ViewHold
클릭이벤트 처리를 위해 interface 정의와 구현이 포함되면서 Adapter 함수가 하는 일에 비해 조금 길어진 느낌이 있네요.

코틀린 고차함수를 적절히 활용하면, OnItemClickListener, OnItemLongClickListener interface를 쓰지 않고, ViewHolder가 View.OnClickListener와 View.OnLongClickListener를 구현하지 않아도 더 간단하게 클릭이벤트를 처리할 수 있습니다.

```suggestion
class ContactsAdapter(
    private var contList: List<Contact>, 
    private val onClick: (Int) -> Unit, 
    private val onLongClick: (Int) -> Unit
): RecyclerView.Adapter<ContactsAdapter.ViewHolder>() {
```

2024-06-29 09:33 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/contacts/MainActivity.kt
> +        GlobalScope.launch(Dispatchers.Main) {
애니메이션에 딜레이를 주기 위해 코루틴을 사용하셨군요!
GlobalScope는 메모리릭을 유발할 수 있어서 사용에 특별한 주의가 필요하며 권장되지 않는 API예요. 5주차 강의를 들으실 때에 GlobalScope의 주의점, Activity의 lifeCycleScope을 함께 학습하시면 좋을 것 같아요.

아래 링크를 참고해 코루틴을 쓰지 않고도 애니메이션에 딜레이를 주는 것도 시도해보시면 좋겠습니다.
https://juliensalvi.medium.com/safe-delay-in-android-views-goodbye-handlers-hello-coroutines-cd47f53f0fbf

2024-06-29 09:33 UTC, kold-brewed commented on app/src/main/AndroidManifest.xml
> +            android:name=".SubActivity"
보통 앱을 시작하자마자 표시되는 LAUNCHER 역할의 Activity의 네이밍이 MainActivity가 됩니다.
다른 Activity들의 네이밍도 기능에 맞게 작성해주시면 좋을 것 같아요!

2024-06-29 09:33 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/contacts/MainActivity.kt
> +                startActivity(intent)
여기서 startActivity를 호출하게되면 현재 Activity Stack은 아래와 같은 순서로 쌓여있습니다.
가장 아래부터
- SubActivity (목록)
- MainActivity (등록)
- SubActivity (목록)
그래서 뒤로가기를 누르면 다시 등록화면이 나오고 한번더 뒤로가기를 누르면 다시 목록화면이 나오게 됩니다.
등록화면은 더이상 필요하지 않으니 종료하고, 목록화면이 1개로 유지될 수 있도록 수정해보시면 좋겠습니다.

2024-06-29 09:33 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/contacts/SubActivity.kt
> +            startActivity(intent)
싱글톤으로 Contact 데이터를 관리하는 것은 여러가지 위험요소가 있어요. 참고 링크와 아래 2가지를 조합해 Contact 목록을 싱글톤으로 만들지 않고도 SubActivity에서 갱신된 목록을 표시해줄 방법도 생각해보시면 좋겠습니다.

1. registerForActivityResult를 이용해 SubActivity에서 Main의 결과를 받아 올 수 있습니다.
2. MainActivity가 종료될 때 setResult와 Intent를 이용해 Contact를 구성하는 정보를 담아 SubActivity로 전달할 수 있습니다.

참고 링크: https://developer.android.com/training/basics/intents/result#launch

2024-06-29 09:33 UTC, kold-brewed commented on app/src/main/res/layout/activity_main2.xml
> +    </LinearLayout>
레이아웃의 깊이가 많이 깊어졌어요. 깊이가 깊어질 수록 화면을 구성하기 위한 계산 시간도 늘어나게됩니다.
이미 최상위에 정의된 ConstraintLayout을 이용해 activity_sub.xml과 같이 각 뷰의 위치 속성을 정의해주면 지금 정의된 모든 LinearLayout을 모두 제거하고도 동일한 화면을 구현할 수 있습니다. 가독성과 깊이를 고려해 너무 깊어지지 않도록 해주시면 좋을 것 같네요!

2024-06-29 12:37 UTC, kold-brewed commented
피드백 요청하신 부분에 대한 내용입니다.

**1. 앱을 설계할 때 구체적인 설계도를 그리는 방법을 알고 싶습니다.**
지금 단계에서는 먼저 구현해야 할 화면들을 간략하게 그려보고, 각 화면들의 기능들을 나열해 본 뒤에 화면간 이동, 혹은 UI 이벤트에 따라 어떤 데이터가 생성되고 전달되어야 할지를 정리하는 정도로도 괜찮지 않을까 합니다. 이후 강의에서 디자인 패턴을 학습하시게되면 레이어를 나눠서 복잡한 비즈니스 로직을 잘 나눠담을지도 고민하는 시간이 있을거예요.

**2. 비효율적인 코드나 장황한 코드를 더 효율적이고 간결하게 고칠 수 있다면 지적해주셨으면 좋겠습니다.**
리뷰 내용으로 대체합니다.

**3. 액티비티 간에 데이터를 연동하기 위해 LiveModel을 써보고 싶었지만, 잘 되지 않았습니다. 액티비티 간에 데이터를 연동할 수 있는 좋은 방법이 있다면 알려주셨으면 좋겠습니다.**
아마도 ViewModel을 말씀해주신거겠죠? 5주차 강의에 있는 내용이라 제가 지금 설명을 드릴 순 없을 것 같아요.
이번 과제에서 요구한 내용은 Intent를 이용해 Activity 간 데이터를 주고 받는 것 이었습니다. 
이후 화면이 더 복잡해지면 SharedPreferences나 SQLite와 같은 로컬 저장소를 이용하고, 지금 구현하신 방법과 같은 싱글톤 패턴을 이용하기도 합니다. 다만, object 클래스는 앱 전반에 걸쳐 어디서든 접근할 수 있게 되고, 앱이 살아있는 동안 내내 유지되기 때문에 메모리릭과 동시성 문제를 잘 고려해 신중하게 사용해야 해서 권장드리지 않습니다.

**4. 메소드끼리 연관되어 있기 때문에 한 메소드를 쓰면서 다른 메소드도 같이 쓰다보니 commit의 단위를 쉽게 잡지 못하겠습니다. 또한 commit 메시지를 어떻게 써야할 지 감이 오지 않습니다. commit을 더 잘하는 방법을 알고 싶습니다!**
Git 사용에 아직 익숙치 않으시다면 당연합니다. 지금은 기능 목록의 1~3개 정도를 1개의 커밋정도로 생각하시고 작성하는 연습을 해보시면 좋을 것 같아요. 새로운 기능을 처음 추가할 때에는 어떤 기능을 구현했는지를 메세지에 담고, 기존 코드를 수정하는 경우에는 어떻게, 왜 수정했는지를 메세지에 담아주시면 좋습니다.

그리고 PR 수정버튼으로 머지 base 브랜치를 kakao-tech-campus-2nd-step2:본인GitHubId로 변경해주세요~

2024-06-29 16:08 UTC, kold-brewed commented on app/build.gradle.kts
> +    implementation("androidx.activity:activity:1.8.0")
이번 주차는 라이브러리를 추가하지 않아도 충분히 구현할 수 있는 과제입니다. 앞으로의 과제들도 라이브러리 별도 안내가 없다면 추가하지 않고 기본 라이브러리 내에서 구현해보셨으면 합니다.

2024-07-01 05:14 UTC, settle54 commented on app/build.gradle.kts
> +        viewBinding = true
검색하다보니 최근에는 findViewById보다 viewBinding 방식이 더 많이 이용된다는 사실을 알았습니다.
다만, 클론코딩강의에서도 그렇고 저도 findView 방식이 더 익숙해서 이 방식으로 했습니다.
다음 과제는 binding 방식을 이용해볼까 하여 기억해둘 겸 넣어둔 거예요!

2024-07-01 05:22 UTC, settle54 commented on app/src/main/java/campus/tech/kakao/contacts/Contact.kt
> +    operator fun get(s: String): String {
MainActivity2.kt, 즉 연락처 상세 화면 코틀린 파일에서
```kotlin
val infos: Array<String> = arrayOf(
            "name", "phoneNumber", "mail", "birth", "gender", "memo"
        )
for (i in 0..5) {
            val value = contact[infos[i]]
``` 
반복문 안에 넣으면 코드가 더 간결해지지 않을까? 싶어서 적용해보았습니다.

2024-07-01 05:30 UTC, settle54 commented on app/src/main/java/campus/tech/kakao/contacts/Contact.kt
> +    var name: String, var phoneNumber: String, var mail: String = "",
```kotlin
Contacts.getList()[position].name = "Amy"
``` 
val이 아니라 var로 설정했는데, 위와 같이 변수를 변경하면 되지 않는 건가요?

2024-07-02 14:21 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/contacts/Contact.kt
> +    operator fun get(s: String): String {
반복문으로 코드량을 줄이고 싶은 마음은 이해합니다만, 이건 일반적으로 객체를 정의하고 사용하는 방식에서 크게 벗어납니다.

보통 get은 List, Map과 같이 많은 양의 데이터를 다루는 컬렉션이나 복잡한 수학연산이 필요한 Vector, Matrix의 원소에 인덱스 연산자([])로 쉽게 접근하기 위해 사용해요. 연락처 정보를 담고있는 Contact 객체는 이에 해당한다고 보기 어렵습니다. 사실 현업에서도 이 연산자를 오버라이드해서 쓸만한 클래스를 정의하는 일은 매우 드뭅니다.

만약 Contact 클래스에 프로퍼티를 추가/제거하거나 네이밍을 수정한다고 가정해볼게요.
수정을 할 때마다 infos 배열 값, get 연산자 오버라이딩 함수도 함께 수정해야하고 "meil"과 같이 오타도 나지 않게 신경써야 할 곳이 너무 많습니다. 

작성해주신 아래 코드 역시 가독성과 유지보수성이 측면에서 다시 한번 생각해봐주셨으면 합니다.
아래 코드에서 만약 mail, birth의 동작을 변경하고 싶다면 어떨까요?
```kotlin
for (i in 0..5) {
        val value = contact[infos[i]]
        if (value.isNotEmpty()) {
            inputFields[i].setText(value)
            if (i >= 2) {
                viewFields[i - 2].visibility = View.VISIBLE
            }
        }
}
```

같은 맥락에서 입력 필드들을 inputFields Array로 관리하기 보다는 모두 개별 변수로 정의하시는 것을 권해드리고 싶어요.

```kotlin
private lateinit var inputName: EditText
private lateinit var inputPhoneNumber: EditText
// ...

inputName.setText(contact.name)
inputPhoneNumber.setText(contact.phoneNumber)
// ...
```
코드 양이 늘어나는 것처럼 보일 수도 있습니다만, 개별 뷰의 동작의 정의부분을 찾기도 수정하기도 수월해집니다.
코딩테스트와는 다르게 현업에서 내가 짠 코드는 다른 사람들의 눈에도 금방 읽힐 수 있도록 쉽게 작성되어야 합니다.

2024-07-02 14:38 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/contacts/Contact.kt
> +    var name: String, var phoneNumber: String, var mail: String = "",
음.. 채원님의 질문을 제가 잘 이해하지 못했고, 알려드리고 싶었던 의도가 전달되지 않은 것 같아서 조금더 설명을 덧붙여볼게요.

과제의 요구사항은 아래와 같았습니다.
- 연락처 정보를 입력한다.
- 입력했던 연락처 정보를 목록에 띄운다.

연락처 정보를 입력하는 상황에서는 저장 버튼을 누를 때, Contact 객체가 생성됩니다. 이후에 Contact객체가 가진 변수들을 수정할 일이 있나요? 또, 입력했던 연락처 정보를 목록에 띄우는 상황에서는 정보를 list에서 가져와 뷰에 할당할 때, Contact 객체가 가진 변수들을 수정할 일이 있나요?

수정할 일이 없고, 수정되어서는 안되는 정보라면 val로 선언해주시면 좋겠습니다.
점점더 코드가 많아지고 이 Contact 객체를 사용하는 곳이 많아지면 var 변수는 코드 파악을 어렵게 만듭니다.

참고: https://velog.io/@wlsrhkd4023/Kotlin-%EB%B6%88%EB%B3%80%EC%84%B1Immutability%EA%B3%BC-%EA%B0%80%EB%B3%80%EC%84%B1Mutability#%EB%B6%88%EB%B3%80%EC%84%B1%EC%9D%B4%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%BC%EA%B9%8C

2024-07-04 12:35 UTC, merged