전남대 Android_장수민_1주차 과제
kakao-tech-campus-2nd-step2/android-contacts pull request #27
Opened 2024-06-28 08:30 UTC by sumintnals

## 연락처 앱 만들기
**기능 요구 사항(1단계)**

- UI를 구성한다.
- 이름과 전화번호를 입력하지 않으면 토스트 메시지를 보여준다.
- 전화번호 입력은 숫자만 가능하게 한다.
- 더보기를 눌러 입력 폼을 확장할 수 있다.
- 생일, 성별, 메모 입력 폼이 등장한다.
- 성별은 둘 중 하나를 선택할 수 있다.
- 저장 버튼을 누르면 '저장이 완료 되었습니다' 라는 토스트 메시지를 보여준다.
- 취소 버튼을 누르면 '취소 되었습니다' 라는 토스트 메시지를 보여준다.

**기능 요구 사항(2단계)**

- 연락처 등록 화면을 구현한다.
- 연락처를 저장하면 목록에 추가된다.
- 저장된 연락처가 많을 경우 목록은 스크롤 되어야 한다.
- 추가된 연락처를 선택하여 상세 화면을 볼 수 있다.
- 연락처 작성 중 뒤로가기 버튼을 누르면 확인 팝업이 나타난다.
- 추가된 연락처는 앱을 다시 실행하면 유지되지 않는다.

추가한 기능
- 저장된 연락처가 없으면 연락처를 추가하라는 문구를 보여줍니다
- 앱 아이콘과 색상을 변경했습니다.

**앱 사진**
<hr>
<img src="https://github.com/kakao-tech-campus-2nd-step2/android-contacts/assets/127755029/a71e194e-cfec-44d3-a2aa-a47f4c8a0382" width="150">
<img src="https://github.com/kakao-tech-campus-2nd-step2/android-contacts/assets/127755029/71ddbc23-9921-4683-9b02-a33727a578ac" width="150">
<img src="https://github.com/kakao-tech-campus-2nd-step2/android-contacts/assets/127755029/e68878ff-e54c-488f-ae78-78770b4b3696" width="150">
<img src="https://github.com/kakao-tech-campus-2nd-step2/android-contacts/assets/127755029/3b65b65a-02e9-4538-92cf-9e3809e93b19" width="150">
<img width="52" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/android-contacts/assets/127755029/e4979267-e71b-41c3-8844-979716a8c138">
<hr>

2024-06-28 08:48 UTC, sumintnals commented
## 🔗1단계 변경사항 링크
### [1단계 커밋](https://github.com/kakao-tech-campus-2nd-step2/android-contacts/pull/27/files/4fee643fc2d98fca3a897ee7d2ca9ed7c355eb6b)

2024-06-30 12:09 UTC, omjoonkim requested changes
> 제가 액티비티 내에 코드로 쓴 부분에서, 함수로 뺄 수 있거나 더욱 간단하게 작성할 수 있는 부분이 있는지, 불필요한 부분은 없는지 궁금합니다.

우선, 진행중인 과제는 구현에 초점이 맞추어져 있기 때문에 해당 부분은 추후 아키텍쳐, 패턴을 학습하실 때 더 중점적으로 코멘트 드릴 수 있을 것 같습니다. :) 다른 분들의 코드를 살펴보며 차이를 생각해보는 것도 좋은 공부방법이 될 수 있을 것 같아요.
> findViewById를 통해 컴포넌트들을 불러오는 부분이 길다는 생각이 드는데, 더욱 복잡한 뷰를 구성할 때에는 어떻게 컴포넌트들을 다 불러오고 관리할 수 있는지 궁금합니다.

viewBinding 사용을 고려해보세요. 코멘트로 남겨두었습니다. ㅎㅎ

> 마찬가지로 xml에서도 복잡한 뷰를 그리면 파일 길이가 너무 길어지는 것 같은데, 이런 경우에는 뷰를 나눠서 그리는지, 아니면 다른 방법이 있는지 궁금합니다.

뷰가 복잡해질 경우 말씀해주신 것처럼 커스텀 뷰로 만들어 활용합니다. 다만 그전에 먼저 현재 작성하신 레이아웃에 불필요한 뷰, 계층은 없는지 확인해보시면 좋을 것 같습니다.
> 제 activity_add_contact.xml 에서도 constraintLayout 안에 또 linearLayout으로 수평 요소들을 만들었는데, 똑같은 코드를 여러 번 사용하다 보니 파일이 300줄이 넘었습니다... 이 부분을 어떻게 해야할지 잘 모르겠습니다. 개선할 방법이 있다면 알려주시면 감사드리겠습니다!

같은 형태가 반복될 경우에는 커스텀 뷰로 만들어 이를 재활용 합니다.  이 [링크](https://developer.android.com/develop/ui/views/layout/custom-views/custom-components)를 참고해보세요. :)

2024-06-30 12:09 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/contacts/AddContactActivity.kt
> +        val name = findViewById<EditText>(R.id.name)
ViewBinding을 사용하시면, 뷰를 선언하기 위한 코드를 줄일 수 있습니다.
https://developer.android.com/topic/libraries/view-binding

2024-06-30 12:09 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/contacts/AddContactActivity.kt
> +            {contactManager.showCancelAlert(this@AddContactActivity, "작성 중인 내용이 있습니다. 정말 나가시겠습니까?")}
사용자에게 보여지기 위해 사용하는 문자열 리소스는 values폴더의 strings.xml 파일에 선언하여 사용하는 것이 좋습니다.

2024-06-30 12:09 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/contacts/AddContactActivity.kt
> +                intent.putExtra("nameText", nameText)
nit; 매직스트링을 사용하는 것보다 상수로 선언해두고 사용하는 것이 추후 관리하기에 더욱 용이합니다.
이 PR에 적용된 다른 매직스트링, 매직넘버들을 한번 상수로 선언한 뒤 사용해보시면 좋을 것 같아요.

ps. nit은 사소한 의견으로 봐주시면 좋을 것 같습니다. :)

2024-06-30 12:09 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/contacts/Contact.kt
> +    var name: String,
data 클래스는 보통 value object의 개념으로 많이 사용 합니다. 꼭 변경되어야 할 필요가 없을때에는 immutable한 선언인 val로 사용하는 것을 고려해보시면 좋을 것 같습니다.

2024-06-30 12:09 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/contacts/ContactAdapter.kt
> +class ContactAdapter(val itemList: List<Contact>,
inflater를 var로 선언한 이유가 있을까요? 변경되지 않는 값이라면 위의 코멘트처럼 val로 선언하는 것을 고려해봐주세요. :)

2024-07-01 05:28 UTC, sumintnals commented on app/src/main/java/campus/tech/kakao/contacts/AddContactActivity.kt
> +        val name = findViewById<EditText>(R.id.name)
알려주셔서 감사합니다! 위에서 알려주신 커스텀 뷰와 뷰 바인딩을 학습해서 과제에도 적용해보도록 하겠습니다!

2024-07-01 05:28 UTC, sumintnals commented on app/src/main/java/campus/tech/kakao/contacts/AddContactActivity.kt
> +            {contactManager.showCancelAlert(this@AddContactActivity, "작성 중인 내용이 있습니다. 정말 나가시겠습니까?")}
넵. 감사합니다! 수정하겠습니다.

2024-07-01 05:28 UTC, sumintnals commented on app/src/main/java/campus/tech/kakao/contacts/AddContactActivity.kt
> +                intent.putExtra("nameText", nameText)
리뷰 감사합니다! 확실히 상수로 선언하고 사용하는 것이 좋을 것 같습니다. 앞으로는 이런 부분에서 상수를 사용하도록 습관을 들이겠습니다!!

2024-07-01 05:28 UTC, sumintnals commented on app/src/main/java/campus/tech/kakao/contacts/Contact.kt
> +    var name: String,
넵 수정하도록 하겠습니다! 알려주셔서 감사합니다!

2024-07-01 05:28 UTC, sumintnals commented on app/src/main/java/campus/tech/kakao/contacts/ContactAdapter.kt
> +class ContactAdapter(val itemList: List<Contact>,
넵! 이것도 수정하도록 하겠습니다. 리뷰해주셔서 감사합니다!

2024-07-02 13:00 UTC, omjoonkim approved these changes
코드리뷰 반영하느라 수고하셨습니다. PR은 머지할게요~!

2024-07-02 13:00 UTC, merged