전남대 Android_최영빈_1주차 과제
kakao-tech-campus-2nd-step2/android-contacts pull request #30
Opened 2024-06-28 08:47 UTC by yb0x00

## 1단계 commit 목록
- https://github.com/yb0x00/android-contacts/commits/step1/
- 시간 부족으로 1단계,2단계 브랜치 merge를 진행하지 못해, 2단계 브랜치에서 PR을 진행하였습니다.

## 코드 작성하면서 어려웠던 점
- 저장한 연락처 중 최근 연락처만 리스트에 뜨는 상황이고, 시간 부족으로 이 이후부터 구현하지 못했습니다.
- RecyclerView 핸들링에 어려움이 있습니다.
- UI 구성에 대해서도 커밋을 쪼개서 나누었는데, 한번에 커밋을 남기는게 더 좋은지 궁금합니다.

## 멘토님이 중점적으로 리뷰해주셨으면 하는 부분
- RecyclerView에서 list에 추가될 때마다 업데이트를 해야하는데,
어떤 부분을 놓쳐서 구현하지 못했는지 궁금합니다.
(라이프사이클을 고려해서 수정또한 진행하였는데 답을 찾지 못했습니다. 아직 라이프사이클과 액티비티에 대한 이해가 전반적으로 부족한 상황인 것 같습니다.)
- 기능 단위에 따라 UI 구현 -> 기능 구현 -> UI 구현 ... 이러한 순서로 진행하다보니 기능 구현에서 막힌 뒤에 UI 구현도 아직 하지 못한 부분이 생겼습니다. 진행 순서에 대한 조언도 받고 싶습니다.

2024-06-29 10:40 UTC, SEO-J17 approved these changes
LGTM!

2024-06-30 12:25 UTC, omjoonkim requested changes
안녕하세요 영빈님. 반갑습니다. :) 코멘트 한번 확인해주시고 궁금한 점은 마찬가지로 코멘트로 달아주세요~!.
> UI 구성에 대해서도 커밋을 쪼개서 나누었는데, 한번에 커밋을 남기는게 더 좋은지 궁금합니다.

추가되는 코드의 양이 얼마나 되는지에 따라 달라질 것 같습니다. 지금 정도의 양이면 하나의 커밋으로 작성하셔도 괜찮습니다. :) 

> RecyclerView에서 list에 추가될 때마다 업데이트를 해야하는데,
어떤 부분을 놓쳐서 구현하지 못했는지 궁금합니다.
(라이프사이클을 고려해서 수정또한 진행하였는데 답을 찾지 못했습니다. 아직 라이프사이클과 액티비티에 대한 이해가 전반적으로 부족한 상황인 것 같습니다.)

onRestart가 언제 불릴 것이라고 생각하시고 코드를 작성하셨을까요? saveContactActivity에서 돌아왔을 때를 알고 싶다면 onActivityResult 함수를 사용해보세요.
적절하게 리스트가 갱신되려면, 데이터가 갱신됬을 때의 적절한 이벤트를 찾아 personList에 데이터를 추가하고, 데이터가 업데이트 되었다는 것을 어뎁터에게 알려주어야(notify) 합니다. 

> 기능 단위에 따라 UI 구현 -> 기능 구현 -> UI 구현 ... 이러한 순서로 진행하다보니 기능 구현에서 막힌 뒤에 UI 구현도 아직 하지 못한 부분이 생겼습니다. 진행 순서에 대한 조언도 받고 싶습니다.

과제애 대한 피드백 관점에서 본다면 하나의 기능을 우선 구현하고, 이후에 다른 기능으로 넘어가는 것이 피드백을 하거나 받기에 더 좋습니다. 다음부터는 기능단위로 한번 진행해보세요. :)

2024-06-30 12:25 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/contacts/ContactListActivity.kt
> +        if (personList.size != 0) {
nit; 
```suggestion
        if (personList.isEmpty()) {
```

2024-06-30 12:25 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/contacts/Person.kt
> +data class Person(var name:String, var phone:String, var email:String?, var birth:String?, var gender:String?, var note:String?) {
data 클래스는 보통 value object의 개념으로 많이 사용 합니다. 꼭 변경되어야 할 필요가 없을때에는 immutable한 선언인 val로 사용하는 것을 고려해보시면 좋을 것 같습니다.

2024-06-30 12:25 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/contacts/SaveContactActivity.kt
> +                showToast("이름은 필수 입력 항목입니다")
토스트로 보여지는 메세지도 strings에서 함께 관리되면 좋을 것 같습니다. :)

2024-06-30 12:25 UTC, omjoonkim commented on app/src/main/res/layout/activity_contact_detail.xml
> +        <androidx.appcompat.widget.LinearLayoutCompat
복잡한 형태의 UI를 표현할 때에는 LinearLayout보다 ConstraintLayout을 주로 사용하는 편입니다. 이는 뷰의 뎁스를 줄여 퍼포먼스 상승과 더 유연한 UI구조를 가능하게 만듭니다.
https://developer.android.com/develop/ui/views/layout/constraint-layout

2024-07-01 06:34 UTC, yb0x00 commented on app/src/main/java/campus/tech/kakao/contacts/Person.kt
> +data class Person(var name:String, var phone:String, var email:String?, var birth:String?, var gender:String?, var note:String?) {
피드백 감사합니다!
   변수 선언에 있어서 '당장 값을 넣으면 val, 아니면 var'과 같이 제대로 생각하지 않고 코드를 작성해왔다는 것을 깨달았습니다. 앞으로는 더 넓은 관점에서 변수의 쓰임을 생각하고 코드를 제대로 작성하고자 합니다!
   말씀해주신 VO의 개념이 생소했습니다. 덕분에 불변 객체의 기능에 대해 고민해볼 수 있었습니다.

2024-07-01 06:56 UTC, yb0x00 commented on app/src/main/java/campus/tech/kakao/contacts/SaveContactActivity.kt
> +                showToast("이름은 필수 입력 항목입니다")
피드백 감사합니다!
그동안 UI를 만들때만 string 리소스를 사용했던 것 같습니다.
말씀해주신 것처럼 앞으로도 출력이 필요한 문자열들을 모두 string 리소스로 관리하여 소프트코딩을 해야겠습니다!

2024-07-02 03:39 UTC, yb0x00 commented on app/src/main/res/layout/activity_contact_detail.xml
> +        <androidx.appcompat.widget.LinearLayoutCompat
피드백 감사합니다!
- 구글링으로 ScrollView에 대해 찾아보니 대게 LinearLayout을 사용하기에
지금까지 '**ScrollView는 LinearLayout 하나를 자식으로 가질 수 있다**'고 생각하고 진행했었고 피드백을 통해 저의 큰 착각임을 깨달았습니다..!
앞으로는 속단하지 말고 공식문서와 기본 강의 내용을 찾아봐 제대로 확인하는 습관을 지니고자 합니다!
- ConstraintLayout이 유연한 UI 구조를 가능하게 만든다는 것에 대해 더 생각해 보고 찾아볼 수 있었습니다. 여담이지만, 덕분에 라이브강의 시간 강사님의 '불필요하게 LinearLayout을 중첩하면 어떤 문제가 발생할까'에 대해 아직 부족한 답변이지만 '뷰 배치에 있어 불필요한 계산량이 많아진다'라고 답할 수 있었습니다:)

**추가적인 질문이 있습니다.**

추가 질문 - 1) 
![질문1](https://github.com/kakao-tech-campus-2nd-step2/android-contacts/assets/169421565/59d8450d-e279-41b8-820b-09c012915191)

메모의 경우 입력 내용이 늘어나면 아래쪽으로만 내용이 추가되게 화면을 만들고 싶어 현재와 같이 코드를 작성한 상황인데요. 옆의 메모 TextView의 경우 항상 메모의 첫번째 줄과 같은 라인에 위치하고 싶어 방법을 찾다가 우선 
(activity_contact_detail.xml 의 231번째 line)
`android:layout_height="0dp"` 
라고 작성했는데 좋은 코드인지 모르겠어서 여쭙고 싶습니다.

추가 질문 - 2)

> onRestart가 언제 불릴 것이라고 생각하시고 코드를 작성하셨을까요? saveContactActivity에서 돌아왔을 때를 알고 싶다면 onActivityResult 함수를 사용해보세요.
적절하게 리스트가 갱신되려면, 데이터가 갱신됬을 때의 적절한 이벤트를 찾아 personList에 데이터를 추가하고, 데이터가 업데이트 되었다는 것을 어뎁터에게 알려주어야(notify) 합니다.

   저는 onRestart()를 사용해서 Activity가 다시 시작될 때마다 personList의 데이터를 읽어와서 화면에 나타내는 방법을 사용해서 코드를 작성했다고 생각하는데요, personList가 바뀌지 않았을 때도 onRestart() 단계에서 매번 화면을 새로 띄우는 방식이 비효율적인가 하는 생각이 듭니다. 현재처럼 코드 작성을 해도 괜찮은 방법인지 여쭙고 싶습니다.

추가 질문 -3)
피드백을 보면 저번 주 금요일 PR이후 추가된 파일에 대해서도 피드백을 주신 것으로 보입니다. PR이후 추가된 파일(step2 요구사항을 모두 구현한 시점)까지 피드백을 진행해 주신 건지 궁금합니다.
**'2주차 step1' PR을 할 때** '1주차 step2의 못다한 내용을 포함하고 있다'고 코멘트를 달지 않아도 되는지 알고 싶어 여쭤봅니다.

감사합니다!!

2024-07-02 08:48 UTC, yb0x00 commented on app/src/main/res/layout/activity_contact_detail.xml
> +        <androidx.appcompat.widget.LinearLayoutCompat
코치님 추가적으로 궁금한 점이 있어 질문 남깁니다.
개인적인 궁금증에 가까운 질문입니다.

#Kotlin 스타일 적용에 대한 질문

1번 코드 : ContactListActivity.kt 84번째 line
`if(nameInfo != null && phoneInfo != null)`

이렇게 코드를 작성했었는데요,

라이브 강의 시간에 '**안전 호출 연산자 ?.**'에 대해 언급하시는 내용을 듣다가
1번 코드와 같이 작성하는 것이 java 스타일로 작성한 코드인가 하는 생각이 들어
2번 코드처럼 작성하는 것이 더 나은 코드인지 고민을 하게 되었습니다.

2번 코드 : ?.를 적용해봄
```
nameInfo?.let { name ->
            phoneInfo?.let { phone ->

                val person = Person(name, phone, emailInfo, birthInfo, genderInfo, noteInfo)
                if (!personList.contains(person)) {
                    personList.add(person)
                }
            }
        }
```

더 나은 코드에 대한 기준은 개인마다 달라 정답이 없는 경우도 많지만,
제 생각에는 이 경우 가독성을 위해 1번처럼 작성하는 게 더 일반적이지 않나 싶은데요. 또 한편으로는 제가 1번 스타일이 익숙해서 그렇게 생각이 드나 싶었습니다.
코치님의 의견이 궁금합니다..!

2024-07-02 12:58 UTC, omjoonkim commented on app/src/main/res/layout/activity_contact_detail.xml
> +            <androidx.constraintlayout.widget.ConstraintLayout
다음에는 ConstraintLayout가 ConstraintLayout를 가진 형태가 아닌 ConstraintLayout하위에 모든 컴포넌트가 같은 뎁스에 위치하도록 레이아웃을 작성해보셔요. 속성을 적절하게 이용한다면 모두 같은 뎁스에 위치시킬 수 있답니다. ㅎㅎ

2024-07-02 12:58 UTC, omjoonkim commented on app/src/main/res/layout/activity_contact_detail.xml
> +        <androidx.appcompat.widget.LinearLayoutCompat
nameInfo와 phoneInfo가 로컬변수인지 혹은 멤버변수인지에 따라 달라질 것 같아요. 로컬변수일 경우 스마트 캐스팅이 되기 때문에 1번을 주로 사용하는 편입니다. 그렇다고해서 항상 멤버 변수의 옵셔널을 해제 할 때 2번 코드스타일로 작성하는 것은 아니에요. 2번 스타일의 경우 인덴트가 점점 늘어나다보니 가독성이 떨어질 수 있습니다. 어렵게 생각할 필요 없이, 함께 협업하는 대상자들끼리 컨벤션을 정하고 그 룰을 따른다고 생각하시면 될 것 같습니다.

2024-07-02 12:58 UTC, omjoonkim approved these changes
추가 질문 - 1)
textview_note의 constraintTop_toTopOf를 parent대신 note_detail로 설정하면 상단 얼라인을 맞출 수 있습니다.

추가 질문 - 2) [Activity Lifecycle](https://developer.android.com/guide/components/activities/activity-lifecycle)을 한번더 확인해보시면 좋을 것 같습니다. 경우에 따라서 앱에 진입할 때마다 데이터를 갱신할수도있고 필요에 의할 때만 갱신할 수도 있습니다. 현재 앱같은 경우에는 특정화면에서 연락처를 추가하고 돌아오기 때문에 행위를 특정지어서 코드를 작성하는 것이 더 좋을 것 같아 보여요.

추가 질문 -3)
넵 모든 코드를 보고 리뷰를 남겼습니다. ㅎㅎ


PR 머지하겠습니다~! 수고하셨어요 ㅎㅎ

2024-07-02 12:58 UTC, merged