충남대_Android_정기주_1주차_과제
kakao-tech-campus-2nd-step2/android-contacts pull request #34
Opened 2024-06-28 08:53 UTC by ddangcong80

어려웠던 점
기능 명세를 우선 적은 다음에 코드를 작성하는 것이 어려웠습니다. 코드를 설계할 당시에는 어떤 레이아웃과 기능을 선택할 수 있는지 명확하지 않아
중간중간 수정을 번복했습니다. 
과제의 요구사항을 모두 충족하지 못했습니다. 연락처 리스트를 구현하는 부분에서 추가해야할 기능들이 너무 많았는데 기능 명세 당시에 생각하지 못했던 부분이라 코드가 복잡해졌습니다.
연락처 추가를 여러번 하면 리스트가 여러개 떠야 하는데 가장 처음 리스트밖에 화면에 나오지 않습니다.

중점적으로 리뷰해주셨으면 하는 부분
과제 2단계 부분이 완벽하지 않아서 우선은 1단계를 중점적으로 리뷰받고싶습니다.

2024-06-29 01:27 UTC, InyoungAum requested changes
고생 많으셨습니다! 

리스트가 안나오는 이유는 스크롤뷰 때문인 것 같은데요 로직상은 문제가 없어 보이고 xml 만 조금 수정하면 잘 나오는 것 같네요 리뷰를 힌트로 수정해 보시길 바랍니다

<img width="195" alt="스크린샷 2024-06-29 오전 10 26 13" src="https://github.com/kakao-tech-campus-2nd-step2/android-contacts/assets/32253123/6f2e536c-e58f-4e4e-98fd-425e17bdce04">

2024-06-29 01:27 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/contacts/ContactAdd.kt
> +class ContactAdd : AppCompatActivity() {
Activity의 네이밍은 항상 뒤에 Activity로 끝나도록 하는것을 권장드립니다

2024-06-29 01:27 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/contacts/ContactAdapter.kt
> +class ContactAdapter(private val context: Context, private val contacts: List<Contact>) : BaseAdapter() {
RecyclerViewAdapter를 사용하지 않으신 이유가 있을까요?

2024-06-29 01:27 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/contacts/ContactAdd.kt
> +            memo.text = null
cleanUpData등의 함수로 따로 빼면 좋을 것 같습니다.

2024-06-29 01:27 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/contacts/ContactAdd.kt
> +                    intent.putExtra("memo", memo.text.toString())
Intent를 통해 데이터를 각각 넘기면 코드가 다소 복잡해지는 면이 있는데요 
parcelable이나 serialization을 사용해서 생성된 contact객체 자체를 넘기는게 좋을 것 같습니다.

2024-06-29 01:27 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/contacts/ContactAdd.kt
> +    private fun checkContact(): Boolean {
이 함수는 String?을 반환하게해여 
null일 경우 message 없이 null이 아닐경우 오류가 있다고 판단 하여 함수가 validation과 toast를 분리할 수 있도록 하는게 좋을 것 같습니다. 

```
val contactValidation = checkContact()
if (contactValidation.isNullOrEmpty()) {
    saveContact()
} else {
    showToast(contactValidation)   
}

```

2024-06-29 01:27 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/contacts/ContactAdd.kt
> +                if (checkContact()) {
checkContact를 할 때의 데이터는 그 타이밍에 edittext에서 가져오고 

또 데이터를 넘기는 시점에 다시 edittext에서 가져오는데요 

이 경우 타이밍 이슈에 의해 데이터가 달라 질 수도 있습니다.

한번만 가져와서 함수 인자로 계속 넘기는 것을 추천드립니다.

2024-06-29 01:27 UTC, InyoungAum commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintLeft_toLeftOf="parent"
이 스크롤 뷰가 필요 없을 것 같네요!

2024-07-02 05:36 UTC, ddangcong80 commented on app/src/main/java/campus/tech/kakao/contacts/ContactAdapter.kt
> +class ContactAdapter(private val context: Context, private val contacts: List<Contact>) : BaseAdapter() {
답변이 늦어서 죄송합니다!
recycler의 개념을 잘 숙지하지 못하고 있어서 사용할 생각을 안 했었습니다. 마침 금주의 강의 내용이 해당 개념이고 step1의 강의를 참고하여 다시 RecyclerView로 작성했습니다.

2024-07-02 05:41 UTC, ddangcong80 commented on app/src/main/java/campus/tech/kakao/contacts/ContactAdd.kt
> +                    intent.putExtra("memo", memo.text.toString())
parcelable이나 serialization을 적용하기 위해 공부를 하던 중에 parcelize라는 방법도 있다는 것을 알았습니다. 과제 수정 시에는 parcelable을 사용하였지만 parcelize가 두 방법의 장점을 가지고 있는 것 같아서 추후에는 이 방법을 사용하는 것이 더 좋은지 궁금합니다.

2024-07-03 01:42 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/contacts/ContactAdd.kt
> +                    intent.putExtra("memo", memo.text.toString())
parcelable 을 사용해보시면 구성이 꽤 번거롭다는 생각이 드실텐데요. 일단 구현법을 아시고 추후에는 parcelize 를 사용하는 것을 추천드립니다.

2024-07-03 12:27 UTC, merged