부산대 Android_노신_1주차_과제
kakao-tech-campus-2nd-step2/android-contacts pull request #7
Opened 2024-06-27 17:31 UTC by Normenghub

### 코드 작성하면서 어려웠던 점
 UI 뼈대 맞추는게 어려웠습니다. 
 또한 변수명을 어떤 식으로 잡아야되는지 중심을 못잡는 느낌입니다. 
 위젯별로 수많은 기능을 담고있는데 이걸 하나하나 찾는 노하우를 빨리 길러야할 것 같습니다. 
 더보기 구상하는데 오래걸렸는데 View를 추가하는 형식으로 구현하긴 했습니다.
 코드가 길어졌는데 다 구상하고 나니 팀원들이 visibility로 숨길수 있다고 들었는데
 이 부분에서 조금 아쉬웠습니다. 보면 라디오그룹 뷰 생성하는데 코드가 많이 길어졌습니다.  
 리스트뷰 클릭시 상세정보를 볼때 visibility를 사용해서 쉽게 구현 할 수 있었던것같습니다. 
 보면 라디오그룹 뷰 생성하는데 코드가 많이 길어졌습니다.  
 클린코드보단 더러워졌다고 생각이듭니다.. 개선점이 많이 필요한것 같습니다. 
 커밋을 언제언제 끊으면서 해야할지 감이 안옵니다.  기능단위라고 하긴하는데.. 도무지 감이 안옵니다.
 함수를 구현하는데 무조건 하나의기능으로 짧게 쓰는게 좋은건지 알고싶습니다. 
  

### 코드 리뷰 시, 멘토님이 중점적으로 리뷰해줬으면 하는 부분
 잘한게 없다고 생각해서 전체적으로 개선점이 시급한 부분에대해서 말씀해주시면 정말 감사드리겠습니다.
 (커밋 , 함수 분리, etc.)

2024-06-30 17:04 UTC, LeeOhHyung requested changes
`노신`님! 반갑습니다.
1주차 과제 구현하시느라 고생많으셨습니다. 코멘트를 읽어보시고, 이해가 잘 안되는 부분이 있다면 편하게 말씀주세요

사용하신 RecyclerView는 2주차 커리큘럼으로 이번 과제리뷰는 1주차 내용만으로 진행하였습니다.

>커밋을 언제언제 끊으면서 해야할지 감이 안옵니다. 기능단위라고 하긴하는데.. 도무지 감이 안옵니다. 함수를 구현하는데 무조건 하나의기능으로 짧게 쓰는게 좋은건지 알고싶습니다.

코드를 보니 고민을 엄청 하신것 같더라구요. 커밋을 잘 나누는것은 저도 항상 어려운것 같습니다. 많은 연습이 필요하고 코드를 작성하기전 무엇을 무엇부터 만들것인지 계획을 잡아두는것이 좋습니다. 흔히 말하는 설계나 software design 이라고도 할수있겠구요. 

과제에서 `AddInfor` 부분만 볼까요. 연락처를 추가하는 화면입니다. 여기서 기능이라고 하는건 `필수항목인 이름,전화번호, 이메일이 입력되어 있는지`, `더보기를 눌렀을때 나머지 위젯들이 보여지는것`, `취소를 누르면 이전화면으로 되돌아감`, `저장 버튼을 누르면 연락처 값들을 이전화면으로 넘겨서 연락처 리스트에 추가됨` 정도로 나열할 수 있습니다. 그럼, 이걸 각각 하나씩 구현하고 커밋의 단위로 만들면 좋겠죠. 물론 이전커밋이 완벽하지 않아서 계속 수정사항이 생길수도 있습니다. 괜찮습니다. 커밋이 항상 새로운 코드만 추가되어야 한다는건 없기 때문에요. 결국 만들어야 하는 기능을 구현하는데에 집중하면 됩니다. 함수를 구현하는것도 마찮가지입니다. 각 기능을 수행하는 함수를 만드는겁니다. 기능을 만드는 과정 중에 `입력값이 잘 입력되었는지 검사할 필요가 있다` 라는걸 인지했다면 이또한 함수로 만들어서 활용할 수 있는것입니다. 동일한 동작을 한다면, 그 함수를 재사용 해볼수도 있겠죠. 그래서 코드를 작성하기 이전에 만들어야 하는것이 무엇인지 파악하고 todo-list를 작성해보면 좀더 수월하지 않을까 합니다.

함수를 너무 잘게 쪼개면, 그또한 파악하는데 수고로움이 생길 수 있습니다. `alertDialog`, `토스트메시지 띄우기`, `입력값 체크` 정도까지 분리하신것은 좋아보이지만, 의도적으로 계속 나눌필요는 없습니다. 하나의 함수가 2~3개 이상의 역할을 수행한다고 생각될때 분리하는것을 추천드립니다. 


#### 참고사항
위 블로그에 있는대로 res/values/ 하위에 `styles.xml` 을 만들고, 사용할 스타일들을 선언해서 사용하는게 일반적입니다. 동일한 속성들을 자주 사용하여 재사용 용이하게 만들고 싶을때나 특정 속성들을 묶어서 이름을 지어주고 싶은 상황들에서 많이 사용하고 있습니다. 


코멘트앞에 `p1`, `p2` 같이 문구가 있는걸 보실수있는데요. 코드리뷰는 텍스트로 의사를 주고받아야 하기 때문에 얼마나 강하게 말하고 싶은지 맥락을 반영하기 힘든 면이 있습니다. 그럴때 저는 [Pn룰](https://blog.banksalad.com/tech/banksalad-code-review-culture/#%EC%BB%A4%EB%AE%A4%EB%8B%88%EC%BC%80%EC%9D%B4%EC%85%98-%EB%B9%84%EC%9A%A9%EC%9D%84-%EC%A4%84%EC%9D%B4%EA%B8%B0-%EC%9C%84%ED%95%9C-pn-%EB%A3%B0) 이라는것을 활용해보고 있습니다. 쉽게 말해 우선순위를 나타낸다고 봐주시면 좋을것 같습니다.

2024-06-30 17:04 UTC, LeeOhHyung commented on app/src/main/java/campus/tech/kakao/contacts/AddInfor.kt
> +private var birthTextView: TextView? = null
p1; 클래스 외부에 변수를 선언하면 static 변수로 만들어지게 됩니다. 클래스 내에서 선언한 지역변수라면, 클래스가 소멸할때 해당 변수들도 메모리에서 해제되게 되는데요. static 변수는 계속 값이 할당되어 있기 때문에 적절한 시점에 해제되지 못하게 됩니다. 그 개수가 매우 많아지게 될경우 메모리가 부족해지는 현상이 발생할 수 있기 때문에 권장드리지 않습니다. clearGlobalVariables() 에서 일부 변수에 null을 넣어서 값을 초기화 시켜주시긴 했지만, String 타입의 변수들은 여전히 값이 남아있게 됩니다 

전역변수로 선언하는 경우는 범용적으로 사용할 수 있는 상수값 / 메소드들로 제한하는것이 좋고, 지금의 경우는 AddInfor Activity 이외에서 사용하지 않기 때문에 범용적이라고 볼수 없습니다. 따라서, 클래스 내에 멤버변수로 선언하는것이 좋을것 같습니다

2024-06-30 17:04 UTC, LeeOhHyung commented on app/src/main/java/campus/tech/kakao/contacts/AddInfor.kt
> +
Activity 를 상속받는 클래스는 -Activity 를 붙여주는게 더 좋을것 같습니다.

2024-06-30 17:04 UTC, LeeOhHyung commented on app/src/main/java/campus/tech/kakao/contacts/AddInfor.kt
> +    }
p3; 토스트 메세지 별로 메소드를 분리하신것은 좋습니다. 하지만, context를 사용하기 위해서 인자로 Button을 넘겨받는것은 Activity의 context를 사용하는것으로 대체할 수 있어보입니다. `this` 를 사용하시면 동일하게 동작하는것을 확인할 수 있습니다

2024-06-30 17:04 UTC, LeeOhHyung commented on app/src/main/java/campus/tech/kakao/contacts/AddInfor.kt
> +    }
### 질문
생일, 성별, 메모 항목의 View를 Activity에서 코드로서 생성하신 이유가 있을까요?

제 예상에는 [더보기] 버튼을 누르지 않았을때, 화면에 보여질 필요가 없는 View 이므로 XML에서 선언하지 않게 하려는 목적이었던것으로 보입니다. 심화된 내용이지만, `ViewStub` 이라는 개념을 사용하면 필요한 시점에 만들어지도록 처리는 가능하지만, 지금 과제에서는 이름/전화번호/이메일 항목과 동일하게 XML에서 선언하되 visibility만 gone으로서 숨김처리하고, [더보기] 버튼을 눌렀을때 visibility를 Visible로 변경하는것으로도 요구사항을 만족할 수 있을것 같긴합니다.

2024-06-30 17:04 UTC, LeeOhHyung commented on app/src/main/java/campus/tech/kakao/contacts/AddInfor.kt
> +private var birthTextView: TextView? = null
혹시, 연락처 작성 화면을 다시 진입하더라도 이전값이 유지되는것을 구현하려고 하셨던 것일수도 있겠네요. `addName` 하나만 확인해보면, 이 변수는 계속 이전의 값을 가지고 있지만, onCreate가 호출될때 TextView에 다시 값을 넣어주는 과정이 없어서 이전값을 유지시켜주는것에 큰 효용이 없는듯합니다. 그리고 데이터 영속성은 2주차 커리큘럼에서 `SharedPreference`를 통한 방법을 배우게될 예정이니 2주차 과제에서 좀더 적절한 방법으로 구현하실 수 있을듯 합니다.

2024-06-30 17:04 UTC, LeeOhHyung commented on app/src/main/java/campus/tech/kakao/contacts/AddInfor.kt
> +    }
p2; [취소] 버튼을 누를때와 [저장] 버튼을 누를때 각각 항목을 검사하는 메소드를 분리하신것 같습니다. 하지만, 결국 필수입력값이 존재하는지 / 선택항목들도 입력이 되었는지를 확인하는것이고 구현부를 보면 코드가 거의 동일하므로 하나의 사실상 하나의 메소드를 사용해도 무방할것 같습니다.

2024-06-30 17:04 UTC, LeeOhHyung commented on app/src/main/java/campus/tech/kakao/contacts/AddInfor.kt
> +                })
p2; `A화면 -> B화면 -> A화면` 으로 되돌아갈때, 특별한 처리없이 화면만 닫는것이라면 startActivity를 할필요는 없습니다. Activity 화면은 Stack 형태로 쌓이게 되는데요! 즉, 새로운 화면을 띄울때마다 기존 화면위에 층층이 포개진다고 생각하시면 편합니다. 따라서, 가장 최상단에 올려져 있는 "연락처 작성" 화면을 종료시켜주는것 만으로도 MainActivity (연락처 리스트) 으로 돌아가게 만들 수 있을듯 합니다. 

- (참고) https://onemask514.tistory.com/43

2024-06-30 17:04 UTC, LeeOhHyung commented on app/src/main/java/campus/tech/kakao/contacts/SpecificInformationActivity.kt
> +        }
p4; `fieldName` 라는 변수는 text가 not empty일때만 사용하므로, if 조건문 내에 위치하는것이 조금더 적절한것 같습니다

2024-06-30 17:04 UTC, LeeOhHyung commented on app/src/main/java/campus/tech/kakao/contacts/MainActivity.kt
> +)
p3; 연락처를 나타내는 클래스를 설계할때 각각의 타입도 적절하게 변경하면 더 좋을것 같습니다. 예를들면, birthday는 날짜를 의미하므로 Date 클래스를 사용하거나, gender는 성별을 의미하므로 별도의 enum class같은 열거형을 만들어서 사용하는것이죠.

```kotlin
enum class Gender {
  MALE, FEMALE, UNKOWN;
}

data clas Contact(
  val gender: Gender
  ...
)
```

그리고, 구현된 앱에서는 `이름`, `전화번호` 는 필수입력값으로, 나머지는 선택입력으로 보여집니다. kotlin data class에는 기본값 (default value) 라고 해서 클래스 인스턴스를 생성할때 인자를 넘겨주지 않을때 사용할 값을 선언할 수 있는데요. 선택항목들이 항상 입력되지 않아도 Contact를 만들수있도록 하는것도 하나의 방법이니 활용하시면 좋을것 같습니다.

```kotlin
data class Contact (
    val name: String,
    val phone: String,
    val email: String = "",
    val birthday: String = "",
    val gender: String = "",

    // enum class로 바꾼다면,
    val gender: Gender = Gender.UNKOWN,
    val memo: String = ""
)
```

2024-06-30 17:04 UTC, LeeOhHyung commented on app/src/main/java/campus/tech/kakao/contacts/AddInfor.kt
> +                }
p2; `연락처` 구성에 필요한 값을 하나하나 넘겨도 되겠지만, ContactInfo 인스턴스 자체를 넘기는 방법도 있습니다. 
만약, 필요한값이 1~2개 정도라면 큰 수고로움이 없겠지만, 연락처 항목이 늘어날수록 주고받아야하는 데이터가 선형적으로 늘어나게 됩니다. 

[Intent로 Class 값 넘기기](https://yuuj.tistory.com/211)
넘기고자 하는 클래스에 `Serializable` 또는 `Parcelable` 을 붙여주면, intent.putExtra(...) 메소드에 담을 수 있습니다. 지금 단계에서는 두개의 차이점을 깊이 아는것 보다는 이런 방법이 있다! 정도만 알고 사용하시고, 추후에 숙달되신다면 차이점도 공부해보시는걸 추천드립니다

2024-07-02 11:52 UTC, Normenghub commented on app/src/main/java/campus/tech/kakao/contacts/AddInfor.kt
> +private var birthTextView: TextView? = null
확인했습니다!

2024-07-02 11:52 UTC, Normenghub commented on app/src/main/java/campus/tech/kakao/contacts/AddInfor.kt
> +
확인했습니다!

2024-07-02 11:52 UTC, Normenghub commented on app/src/main/java/campus/tech/kakao/contacts/AddInfor.kt
> +    }
확인했습니다!

2024-07-02 11:53 UTC, Normenghub commented on app/src/main/java/campus/tech/kakao/contacts/AddInfor.kt
> +    }
예상하신게 맞습니다. visibility를 구현 후에 알아서 그냥 진행 하였습니다.

2024-07-02 11:53 UTC, Normenghub commented on app/src/main/java/campus/tech/kakao/contacts/AddInfor.kt
> +    }
확인했습니다!

2024-07-02 11:53 UTC, Normenghub commented on app/src/main/java/campus/tech/kakao/contacts/AddInfor.kt
> +                })
확인했습니다!

2024-07-02 11:53 UTC, Normenghub commented on app/src/main/java/campus/tech/kakao/contacts/SpecificInformationActivity.kt
> +        }
확인했습니다!

2024-07-02 11:53 UTC, Normenghub commented on app/src/main/java/campus/tech/kakao/contacts/MainActivity.kt
> +)
확인했습니다!

2024-07-02 11:53 UTC, Normenghub commented on app/src/main/java/campus/tech/kakao/contacts/AddInfor.kt
> +                }
확인했습니다!

2024-07-04 03:15 UTC, LeeOhHyung commented
수정해서 올려주신 커밋들도 확인했습니다. 고생많으셨습니다.

2024-07-04 03:15 UTC, merged