강원대_Android_이아림_1주차과제
kakao-tech-campus-2nd-step2/android-contacts pull request #8
Opened 2024-06-27 17:51 UTC by arieum

2024-06-27 17:58 UTC, arieum commented
- UI가 생각보다 고역이었습니다. 리니어레이아웃에서 두 텍스트뷰를 양끝단에 두기위해 space공간을 두는점, softkeyboard가 화면을 가리지 않게 하기 위해 manifest를 수정해야 했던점... 이러한 사소한 부분들이 발목을 많이 잡았습니다
- 역시나 RecyclerView+Adapter를 구현하는 게 만만치 않았습니다 동시에 Intent도 자칫 잘못하면 갑자기 다른 화면으로 넘어가 난행이었던 것 같습니다
- 코드 작성하면서 느꼈지만, 내가 클래스명을 지었음에도 계속해서 헷갈렸던것 같습니다. 어떤 클래스가 어떤 기능을 하는지 한눈에 알 수 있는 이름을 짓는다는건 생각보다 연습이 많이 필요한 것 같습니다

2024-06-30 09:19 UTC, mkSpace requested changes

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/MainActivity.kt
> +    lateinit var emptyTextview: TextView
<img width="565" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/android-contacts/assets/24197741/93913ff5-2e22-468e-a8b3-a3d8b6b803d3">

IDE를 확인해보시면 외부에서 접근하지 않는 변수는 private으로 변경하라는 주의문구가 나올거에요. 개발하시면서 IDE가 하는 주의사항에 유의하셔서 개발하시면 좋을 것 같습니다.
언제 private을 써야 하는지 판단하기 힘드시다면 private을 기본적으로 작성하시고 필요하실때 접근 제한자의 범위를 하나씩 열어보시는게 공부하실 때 도움 되실 겁니다!

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/MainActivity.kt
> +        recyclerView = findViewById<RecyclerView>(R.id.recyclerView).apply {
apply scope function을 의도대로 잘 작성해주셨네요! 👍

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/MainActivity.kt
> +    var personList: MutableList<Person> = mutableListOf<Person>()
personList의 책임 주체가 어디인지 분명히 하는게 좋을 것 같네요. 이는 멘티분이 생각하시는 대로 일관성있게 작성하시는게 중요합니다.
Android MVC 패턴에서 SSOT (Single Source of Truth)를 챙기기에는 현재 단계에서는 생각할 부분이 많고 모호한 부분이 존재한다고 생각합니다. 현재 작성해주신 코드에서는 SSOT가 MainActivity일 수도 PersonAdapter일 수도 있겠네요. 누가 책임을 가질지는 모호할 수 있지만 중요한 것은 두 객체간의 공유하는 데이터가 있을 때 이를 변경하는 것은 하나의 클래스에서 해야만 한다는 것입니다. 
지금 작성해주신바로는 Adapter, Activity 모두 PersonList에 접근해서 데이터를 변경할 수 있네요. 
이를 해결하기 위해서 두 가지 방법으로 리팩토링 할 수 있습니다.

1. MainActivity가 데이터를 관리하게 한다고 한다면 Adapter를 최대한 멍청하게 만드셔야 합니다. 지금과 같은 방식으로 데이터의 변경에 대한 부분을 Adapter를 사용하는 쪽에서 책임을 지는것 입니다. (데이터를 추가하고, 데이터의 변경이 있음을 알리는 등) 이 방법의 경우 장점은 Adapter를 최대한 멍청하게 유지함으로써 다른 View에서도 사용하기 편리할 수 있습니다. 하지만 단점은 데이터 추가 및 변경을 사용하는 쪽에서 하나하나 다 알려줘야 하기 때문에 사용하는 곳(MainActivity 등 View)의 역할이 더더욱 커질 수 있겠네요.

2. Adapter가 데이터를 관리하는 방식입니다. Adapter가 데이터를 관리해서 MainActivity는 단순히 Adapter에 초기 데이터를 넘겨주고 데이터의 추가 및 수정, 변경 감지에 대한 책임을 Adapter로 미뤄버리는 것입니다. 이 방식의 장점은 MVC  패턴의 가장 큰 단점인 Activity가 너무 많은 역할을 하는 상태(God Object)를 완화시킬 수 있겠네요. 하지만 이 방식도 단점이 존재합니다. 바로 해당 Adapter를 쓰는 View와 강결합된다는 것입니다.

사실 이 문제는 지금 안드로이드를 시작하는 단계에서 생각하기에는 무거운 주제일 수 있습니다. 앞으로 안드로이드를 공부하시다보면 여러가지 아키텍처에 대해서 배우실 겁니다. 현재 단계에서 존재하는 이러한 단점을 인지하고 있으면 추후 다른 아키텍처나 또 다른 Adapter 들을 배우실 때 도움이 되실 거에요. 두 가지 방식 중 한 가지 방식으로 리팩토링을 진행해 보셔도 좋고 힘드시다면 단순히 생각만 해보셔도 좋을 것 같습니다 ~

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/MainActivity.kt
> +            startActivity(intent)
이 방식은 Adapter가 가지는 데이터를 신뢰한다는 생각이 깔려있네요. 이런 부분에서 데이터 일관성이 깨질 수 있습니다. 만일 데이터 주체가 MainActivity에 있다면 단편적인 정보(index 등)을 가지고 MainActivity에서 조회하는 방법을 사용할 수 있겠네요.

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/MainActivity.kt
> +    private fun updateUI() {
updateUI는 데이터가 변경이 될 때마다 이뤄져야 하는 것으로 보입니다. Observable 패턴을 쓰지 않고는 이러한 변경을 감지하는게 힘들 수 있겠네요. 이를 위해 adapter에서 데이터 감지를 포착해주는 콜백 메서드가 있습니다. 이를 활용해보세요.

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/MainActivity.kt
> +        }
팁입니다! View의 Visibility를 세팅하는 확장함수들이 있습니다.
View.isVisible 함수를 사용해보세요! 더욱 직관적이게 코드를 작성할 수 있습니다.

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/Person.kt
> +class Person(
Person 이라는 객체는 정보만을 담고 있고 여러 객체에 의해 송/수신 되는 객체입니다. 멀티 스레드 환경에서는 클래스를 항상 불변 객체로 유지하는 게 좋습니다. Kotlin의 data class에 대해서 학습해보세요!

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/ResiterContact.kt
> +    lateinit var nameForm: EditText
여기도 기본적으로 private을 다 달아주세요

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/ResiterContact.kt
> +        }
xml에서 정의한 View를 코드로 갖고 온 후에 작성하는게 더 나아보입니다.
코드는 항상 잘 볼 수 있는 형태를 유지하는 게 좋습니다. 엄밀히 말하면 View를 사용하는데 xml에 어떻게 정의되어 있는지 살펴보는것은 불필요해 보이네요. setupViews() 이름의 함수를 따로 만들어서 View를 가지고 오는 함수 그리고 그 View를 사용하는 코드를 분리하는게 더 나아보입니다.

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/ResiterContact.kt
> +class ResiterContact : AppCompatActivity() {
객체의 이름은 그 객체의 역할을 분명히 밝혀야 합니다. RegisterContact는 Activity이기에 RegisterContactActivity 정도로 변경하면 좋겠네요.

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/ResiterContact.kt
> +            //Log.d("Log", sex)
불필요한 주석은 과감히 삭제해주세요.
주석은 코드를 봤을 때 한 번에 이해 하기가 힘들경우 사용하며 최대한 코드로 잘 표현하는게 좋습니다.
위의 경우일 때 사용하시고 꼭 사용하셔야 한다면 그 이유를 같이 적어주세요.

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/ResiterContact.kt
> +            birth = if (birthForm.text.toString().isNotEmpty()) birthForm.text.toString() else null.toString()
null인 경우 꼭 null String을 반환해야 할까요? null인 경우 그냥 전달하지 않으셔도 괜찮습니다. 이 데이터를 받을 때 getStringExtra를 사용할 텐데 이는 nullable 입니다!

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/ResiterContact.kt
> +                    show()
apply scope function은 기본적으로 타겟이 되는 객체의 속성을 적는다는 행동을 하기 위한 용도로 많이 쓰입니다. show()는 속성을 세팅하기 위한 함수는 아닌 것 같네요.
AlertDialog.Builder().apply {}.show() 정도로 고쳐볼 수 있을 것 같아요

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/ViewContact.kt
> +class ViewContact : AppCompatActivity() {
여기도 동일하게 이름 변경해주세요!
네이밍 관련해서 제안드리자면 아이템에 대한 자세한 정보를 제공할 때 보통 ~~Details를 많이 사용합니다.
이는 제안 사항이고 편하신 대로 네이밍 해주세요!

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/res/layout/activity_resiter_contact.xml
> +        app:layout_constraintRight_toRightOf="parent"></ImageView>
```suggestion
        app:layout_constraintRight_toRightOf="parent"/>
```
이렇게 하는게 오해의 소지가 없겠네요.

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/res/layout/activity_resiter_contact.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
ConstraintLayout는 왠만한 경우면 Depth를 1로 유지하면서 모든 걸 표현할 수 있습니다. 다만, depth가 깊어질 수록 성능에 악영향을 주는데요. 현재 ViewGroup들을 여러개 사용중이신데 이럴 경우 차라리 ConstraintLayout을 사용하지 않고 LinearLayout, FrameLayout 등을 여러개 사용하시는게 더 낫습니다. ViewGroup을 사용하지 말고 작성해보시는것을 추천드립니다.

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/res/layout/activity_resiter_contact.xml
> +        android:layout_width="@dimen/edittext_width"
여기서는 match_parent를 쓰는게 더 좋아보이네요. 더보기 버튼뿐 아니라 더보기 버튼 공간을 포함한 한 줄 (좌우 모두 포함)을 클릭했을 떄 작용하는게 UX 면에서 더 나아 보이네요.

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/res/layout/activity_resiter_contact.xml
> +            android:id="@+id/detail_button"
텍스트뷰에서 버튼처럼 클릭 이펙트를 주는 방식으로
android:background="?attr/selectableItemBackground"
를 사용할 수 있습니다.

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/MainActivity.kt
> +                viewAdapter.notifyDataSetChanged()
MainActivity에서 데이터를 관리한 다면 이 두 메서드는 묶어서 하나의 메서드로 작성할 수 있겠네요.

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/MainActivity.kt
> +                viewAdapter.notifyDataSetChanged()
notifyDataSetChanged()를 사용하시면 IDE에서 주의사항을 알려줄 텐데 이 메서드는 효율적인 방법이 아닙니다. 한 번 찾아보시겠어요?

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_margin="16dp"
end 및 bottom 쪽으로만 margin이 필요한데 전체 margin을 주신 이유가 있을까요?

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/MainActivity.kt
> +            setHasFixedSize(true)
성능을 위한 코드를 잘 작성해 주셨네요.
혹시 이 함수가 어떤 역할을 하는지 알고 계신가요?

2024-06-30 09:19 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/contacts/MainActivity.kt
> +                val birth = data?.getStringExtra("birth") ?: ""
이 정보들이 null일 때 꼭 빈 String을 가져야 하나요? 그냥 null을 쓰면 안될까요?

2024-06-30 09:23 UTC, mkSpace commented
안녕하세요 앞으로 6주간 코드 리뷰를 도와드리게 된 제리 멘토라고 합니다.
전반적으로 구현 사항을 잘 구현해주셨네요!
제가 남겨드린 리뷰 살펴보시고 이해가 힘드신 부분은 추가 의견 남겨주시면 바로 답변 남겨드리겠습니다.
의견을 작성하기 힘든 부분들은 추후 멘토링 시간을 이용해서 자세히 알려드릴 수 있으면 좋겠습니다.
감사합니다 ~

2025-09-19 08:27 UTC, closed without merging