강원대_Android_김동한 1주차 과제
kakao-tech-campus-2nd-step2/android-contacts pull request #9
Opened 2024-06-27 18:04 UTC by Han961004

코드 작성하면서 어려웠던 점
- 아직도 작성을 하다보면 commit을 한꺼번에 하는 경향이 있는데 고쳐야 할 것 같습니다.
- .xml 파일의 UI 구성할 때 완전히 "실행 결과" 처럼 똑같이  나와야 할 것 같은데 잘 안되서 어렵습니다.
- 이미지 파일을 구해와서 Resize하는 부분

멘토 님이 중점적으로 리뷰해줬으면 하는 부분
- .xml UI 에서 성별이랑 radioGroup을 LinearLayout 으로 한줄에 나오도록 만들었는데 "실행 결과" 처럼 만들고 싶습니다. (칸 안에 radioGroup) 
- MainActivity.kt 에서 기능적인 부분을 평가 받고 싶습니다.

2024-06-28 13:17 UTC, kold-brewed requested changes
안녕하세요 동한님 :)
6주동안 Step2 과제 진행을 도와드릴 콜드입니다.
1단계 요구사항을 모두 만족하도록 MainActivity도 잘 작성해주셨습니다.
코멘트 남겨드린 내용만 한번 확인 부탁드리고, 2단계도 화이팅입니다 💪

2024-06-28 13:17 UTC, kold-brewed commented on README.md
> +모든 피드백을 반영하였으면 다음 단계를 시도하고 프로세스를 반복한다.
마크다운은 별다른 도구없이도 글을 깔끔하고 예쁘게 작성할 수 있어서 프로젝트 README 파일뿐 아니라 GitHub PR의 description 등 현업에서도 명세를 작성할 때 자주 사용됩니다.

아래 마크다운 문법에서 제목, 목록, 줄바꿈 등을 적절히 활용해 위의 README.md 파일에 프로젝트에 구현된 기능 내용이 잘 담길 수 있게 정리해주시면 좋을 것 같아요!
https://docs.github.com/ko/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

2024-06-28 13:17 UTC, kold-brewed commented on app/src/main/res/layout/activity_main.xml
> +                </LinearLayout>
LinearLayout을 이용해서 같은 줄에 표시되도록 수정을 해주셨군요👍 

사실 성별 입력은 RadioButton만으로도 충분히 제기능을 할 수 있기 때문에, 작성해주신 방법 혹은 TextView+RadioGroup으로 작성해도 괜찮아보여요.

질문하신 것과 같이 만약 1단계 실행 결과처럼 가로가 꽉 찬 EditText 영역 내에 RadioGroup을 위치시키고 싶으시다면, ConstraintLayout 혹은 RelativeLayout을 이용해 볼 수 있습니다. 이 두 레이아웃은 뷰를 상대적인 위치 관계에 따라 배치시킬 수 있어서 LinearLayout과 달리 서로 다른 두개의 뷰를 겹치게 할 수 있습니다. 성능적인 측면에서 더 권장되는 ConstraintLayout으로 시도해보시면 좋을 것 같아요!

2024-06-28 13:26 UTC, kold-brewed commented
PR 상단 우측에 Edit 누르신 뒤에 머지할 base브랜치를 main 대신 GitHub 사용자 이름으로 만들어진 브랜치로 변경부탁드려요~

2024-06-29 12:48 UTC, kold-brewed commented on app/src/main/res/layout/activity_main.xml
> +                        android:layout_weight="1"/>
xml에서 뷰 속성은 보통 id, layout_width, layout_height 순으로 정의합니다. 코드 컨벤션은 Ctrl + Alt + L(Reformat code)으로 한번에 맞추실 수 있으니 커밋 전에 한번씩 정리해 주시면 좋겠습니다!

2024-07-01 16:47 UTC, kold-brewed approved these changes
2단계까지 잘 작성해주셨네요! 수고하셨습니다.

2024-07-01 16:47 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/contacts/ContactAddActivity.kt
> +     * 질문, private lateinit 이렇게 하는 방법을 알았는데 함수를 관리하기 쉽다는 장점을 알았습니다. 단점이 있을까요?
lateinit 키워드를 이용하면 변수를 정의하는 시점에 초기화해주지 않아도 되기 때문에 변수를 nullable하지 않게 만들 수 있습니다.
변수가 non-null이라면 사용할 때마다 null-check를 하지 않아도 되기 때문에 코드 가독성을 높일 수 있어요.

대신 앱이 죽을수도 있다는 단점이 있습니다. 초기화 하기 전에 접근하면 Exception이 발생하고, 적절히 예외처리하지 않으면 앱이 죽게됩니다. 지금은 코드가 단순하고 onCreate에서 모두 초기화가 되고 있어서 문제가 없습니다만, 점점 클래스가 거대해지면서 함수가 나뉘고, 파일로 나누다보면 초기화 하기 전에 변수에 접근하는 실수가 생깁니다. 그런 상황에서는 변수에 접근하기전에 ::name.isInitialized를 통해 초기화 여부를 체크하고 사용하면 Exception을 막을 수 있습니다.

그래서 너무 남발해서 사용하기보다는 지금처럼 명확하게 onCreate에서 초기화해주는 상황이 확실하면서 변수를 non-null로 만드는 것의 장점이 확실할 때에만 쓰시길 권해드리고 싶어요.

2024-07-01 16:47 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/contacts/ContactAddActivity.kt
> +                // putExtra( 키 , 값 ) <==> getStringExtra( 키 , 값 ) 키가 같아야 됨
그래서 키값은 아래와 같이 상수로 정의해서 사용하면 오타낼 확률을 줄일 수 있습니다!
```kotlin
private const val CONTACT_NAME = "contact_name"

putExtra(CONTACT_NAME, name.text.toString())
```

2024-07-01 16:47 UTC, merged

2024-07-02 05:33 UTC, Han961004 commented on app/src/main/java/campus/tech/kakao/contacts/ContactAddActivity.kt
> +     * 질문, private lateinit 이렇게 하는 방법을 알았는데 함수를 관리하기 쉽다는 장점을 알았습니다. 단점이 있을까요?
궁금한 점이 하나 더 있습니다. 따로따로 기능 설정안하고, 함수로 처리하고 같은 효과를 내는 것이 더 효율적일까요? (보편적일까요?)

{
  ...

  // 취소 버튼 리스너
  cancelBtn.setOnClickListener {
      **_showCancelConfirmationDialog()_**
  }
  
  // 뒤로 가기 버튼 처리
  onBackPressedDispatcher.addCallback(this, object : OnBackPressedCallback(true) {
      override fun handleOnBackPressed() {
          **_showCancelConfirmationDialog()_**
      }
  }) 
  ...
}


// 취소 확인 다이얼로그 표시
**_private fun showCancelConfirmationDialog() {_**
    AlertDialog.Builder(this)
        .setMessage("작성 중인 내용이 있습니다. 정말 나가시겠습니까?")
        .setPositiveButton("작성하기") { dialog, which -> }
        .setNegativeButton("나가기") { dialog, which ->
            Toast.makeText(this, "취소되었습니다.", Toast.LENGTH_SHORT).show()
            finish()
        }
        .show()
}

2024-07-02 13:24 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/contacts/ContactAddActivity.kt
> +     * 질문, private lateinit 이렇게 하는 방법을 알았는데 함수를 관리하기 쉽다는 장점을 알았습니다. 단점이 있을까요?
맞아요. 두 위젯이 완전히 동일한 기능을 수행해야 한다면 말씀하신 것처럼 함수로 묶어내는 것이 일반적입니다.

안드로이드는 iOS와 달리 기본적으로 화면상에 백버튼이 있어서 이렇게 백버튼과 화면에 넣은 버튼이 동일한 기능을 수행하도록 하는 요구사항은 자주 마주치게 되실거예요.